FROM node:18-alpine AS build

WORKDIR /workspace/samha-frontend

COPY samha-frontend/package.json samha-frontend/package-lock.json ./
RUN npm ci

COPY samha-frontend/ ./
RUN npm run build -- --configuration production

FROM nginx:1.27-alpine

COPY nginx.docker.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/samha-frontend/dist/samha-frontend /usr/share/nginx/html

EXPOSE 80
